description = "A cool blog theme"
features = "blog"
homepage = "https://github.com/Zanthed/eridan.me-theme"
license = "MIT"
licenselink = "https://github.com/Zanthed/eridan.me-theme/blob/master/LICENCE.txt"
name = "eridan.me-theme"
tags = "blog"

[author]
  homepage = "https://eridan.me/"
  name = "June"
  username = "Zanthed"
